# Generated by Django 5.1.6 on 2025-03-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="for_sale",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
