# Generated by Django 5.1.6 on 2025-03-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_books_for_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="original_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
