# Generated by Django 5.1.6 on 2025-02-24 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_alter_cart_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "Cart", "verbose_name_plural": "Cart"},
        ),
    ]
