# Generated by Django 5.1.6 on 2025-03-04 18:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_alter_cart_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "Basket", "verbose_name_plural": "Baskets"},
        ),
    ]
