# Generated by Django 5.1.5 on 2025-02-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("book_name", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                (
                    "picture",
                    models.ImageField(blank=True, null=True, upload_to="book_pics/"),
                ),
            ],
        ),
    ]
